version: "3"
services:
  couch_master:
    image: "ibmcom/couchdb3:3.2.1"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    links:
      - couch_slave
    volumes:
      - data_master:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.129.57
    container_name: couch_master
    networks:
      couchdb_nw:
        ipv4_address: 172.26.129.57

  couch_slave:
    image: "ibmcom/couchdb3:3.2.1"
    restart: always
    ports:
      - "15984:5984"
    volumes:
      - data_slave:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.131.146
    container_name: couch_slave
    networks:
      couchdb_nw:
        ipv4_address: 172.26.131.146

volumes:
  data_master:
  data_slave:

networks:
  couchdb_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
