# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: yuanbo
instance_flavor: 	uom.mse.1c4g
instance_network: gh2-uom-internal
# Volume
volumes:
  - vol_name: test-vol-1
    vol_size: 10
  - vol_name: test-vol-2
    vol_size: 10
  # - vol_name: couchDB2-vol-1
  #   vol_size: 5
  # - vol_name: couchDB2-vol-2
  #   vol_size: 75
  # - vol_name: couchDB3-vol-1
  #   vol_size: 5
  # - vol_name: couchDB3-vol-2
  #   vol_size: 30

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: test
    volumes: ["test-vol-1","test-vol-2"]
  # - name: couchDB-2
  #   volumes: ["couchDB2-vol-1", "couchDB2-vol-2"]
  # - name: couchDB-3
  #   volumes: ["couchDB3-vol-1", "couchDB3-vol-2"]
