---
- name: Install dependencies
  become: yes
  ansible.builtin.pip:
    name: ['mastodon.py,nltk,couchdb']
    state: latest
- name: Download vader_lexicon
  become: yes
  command: python3 -c "import nltk; nltk.download('vader_lexicon')"

- name: Copy directory to remote machine
  copy:
    src: "{{ src_file }}"
    dest: "{{ dest_dir }}"

- name: start Harvesting
  become: yes
  ansible.builtin.shell: nohup python3 Python/stream.py > /dev/null 2>&1 &
  async: 0
  poll: 0
