- hosts: Dev
  vars_files:
    - host_vars/deploy_vars.yaml
  become: yes
  gather_facts: false
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/yuanbo.pem
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  roles:
    - role: deploy
